version: '3.8'
services:
  bot:
    build:
      context: .
    container_name: discord_bot
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app
    command: ["node", "index.js"]
