// 🏅 Catálogo de logros (datos). El motor (aplicar eventos, reclamar, anunciar) está en systems/achievementsSystem.js;
// aquí solo están las definiciones. Para añadir un logro, una fila nueva en su lista; los de idioma de Plex vienen
// de systems/plexIdiomas y se añaden al final.

const CATALOG = [
    {
        id: "primer_mensaje",
        name: "Hola Mundo",
        desc: "Envía tu primer mensaje válido",
        category: "social",
        event: "message_count",
        metric: "sum",
        target: 1,
        rewardCoins: 100,
    },
    {
        id: "charlatan_100",
        name: "Charlatán",
        desc: "Envía 100 mensajes válidos",
        category: "social",
        event: "message_count",
        metric: "sum",
        target: 100,
        rewardCoins: 400,
    },
    {
        id: "veterano_1000",
        name: "Veterano",
        desc: "Envía 1000 mensajes válidos",
        category: "social",
        event: "message_count",
        metric: "sum",
        target: 1000,
        rewardCoins: 1500,
    },
    {
        id: "cronista_2500",
        name: "Cronista",
        desc: "Envía 2500 mensajes válidos",
        category: "social",
        event: "message_count",
        metric: "sum",
        target: 2500,
        rewardCoins: 2500,
    },
    {
        id: "leyenda_chat_5000",
        name: "Leyenda del Chat",
        desc: "Envía 5000 mensajes válidos",
        category: "social",
        event: "message_count",
        metric: "sum",
        target: 5000,
        rewardCoins: 5000,
    },
    {
        id: "voz_60",
        name: "Locutor",
        desc: "Acumula 60 minutos en voz",
        category: "xp",
        event: "voice_minutes",
        metric: "sum",
        target: 60,
        rewardCoins: 300,
    },
    {
        id: "voz_300",
        name: "Podcaster",
        desc: "Acumula 300 minutos en voz",
        category: "xp",
        event: "voice_minutes",
        metric: "sum",
        target: 300,
        rewardCoins: 1200,
    },
    {
        id: "voz_1000",
        name: "Radio Duende",
        desc: "Acumula 1000 minutos en voz",
        category: "xp",
        event: "voice_minutes",
        metric: "sum",
        target: 1000,
        rewardCoins: 3500,
    },
    {
        id: "xp_1000",
        name: "Aprendiz",
        desc: "Gana 1000 XP total",
        category: "xp",
        event: "xp_gain",
        metric: "sum",
        target: 1000,
        rewardCoins: 300,
    },
    {
        id: "xp_5000",
        name: "Erudito",
        desc: "Gana 5000 XP total",
        category: "xp",
        event: "xp_gain",
        metric: "sum",
        target: 5000,
        rewardCoins: 1500,
    },
    {
        id: "xp_20000",
        name: "Sabio",
        desc: "Gana 20.000 XP total",
        category: "xp",
        event: "xp_gain",
        metric: "sum",
        target: 20000,
        rewardCoins: 5000,
    },
    {
        id: "nivel_10",
        name: "Subiendo",
        desc: "Alcanza nivel 10",
        category: "xp",
        event: "xp_level",
        metric: "max",
        target: 10,
        rewardCoins: 500,
    },
    {
        id: "nivel_25",
        name: "Experimentado",
        desc: "Alcanza nivel 25",
        category: "xp",
        event: "xp_level",
        metric: "max",
        target: 25,
        rewardCoins: 1500,
    },
    {
        id: "nivel_40",
        name: "Avanzado",
        desc: "Alcanza nivel 40",
        category: "xp",
        event: "xp_level",
        metric: "max",
        target: 40,
        rewardCoins: 3500,
    },
    {
        id: "nivel_60",
        name: "Elite",
        desc: "Alcanza nivel 60",
        category: "xp",
        event: "xp_level",
        metric: "max",
        target: 60,
        rewardCoins: 7000,
    },
    {
        id: "casino_primera",
        name: "Primera Apuesta",
        desc: "Realiza tu primera apuesta",
        category: "casino",
        event: "casino_bet",
        metric: "sum",
        target: 1,
        rewardCoins: 150,
    },
    {
        id: "casino_10000",
        name: "High Roller",
        desc: "Apuesta 10.000 monedas acumuladas",
        category: "casino",
        event: "casino_bet",
        metric: "sum",
        target: 10000,
        rewardCoins: 800,
    },
    {
        id: "casino_50000",
        name: "Mesa VIP",
        desc: "Apuesta 50.000 monedas acumuladas",
        category: "casino",
        event: "casino_bet",
        metric: "sum",
        target: 50000,
        rewardCoins: 3500,
    },
    {
        id: "casino_wins_25",
        name: "Golpe de Suerte",
        desc: "Consigue 25 victorias en casino",
        category: "casino",
        event: "casino_win_count",
        metric: "sum",
        target: 25,
        rewardCoins: 1200,
    },
    {
        id: "casino_wins_100",
        name: "Imparable",
        desc: "Consigue 100 victorias en casino",
        category: "casino",
        event: "casino_win_count",
        metric: "sum",
        target: 100,
        rewardCoins: 4500,
    },
    {
        id: "casino_profit_5000",
        name: "Con Beneficios",
        desc: "Gana 5.000 monedas netas en casino",
        category: "casino",
        event: "casino_net_profit",
        metric: "sum",
        target: 5000,
        rewardCoins: 2000,
    },
    {
        id: "casino_profit_20000",
        name: "Magnate del Azar",
        desc: "Gana 20.000 monedas netas en casino",
        category: "casino",
        event: "casino_net_profit",
        metric: "sum",
        target: 20000,
        rewardCoins: 7500,
    },
    {
        id: "casino_losses_50",
        name: "Cabezota",
        desc: "Pierde 50 partidas en casino",
        category: "casino",
        event: "casino_loss_count",
        metric: "sum",
        target: 50,
        rewardCoins: 1800,
        hidden: true,
    },
    {
        id: "cripto_primera",
        name: "Inversor Novato",
        desc: "Haz tu primera compra cripto",
        category: "cripto",
        event: "cripto_buy_count",
        metric: "sum",
        target: 1,
        rewardCoins: 150,
    },
    {
        id: "cripto_10_ops",
        name: "Trader Activo",
        desc: "Completa 10 operaciones cripto",
        category: "cripto",
        event: "cripto_ops_count",
        metric: "sum",
        target: 10,
        rewardCoins: 900,
    },
    {
        id: "cripto_50_ops",
        name: "Trader Pro",
        desc: "Completa 50 operaciones cripto",
        category: "cripto",
        event: "cripto_ops_count",
        metric: "sum",
        target: 50,
        rewardCoins: 4000,
    },
    {
        id: "cripto_vol_20000",
        name: "Volumen Alto",
        desc: "Mueve 20.000 monedas en cripto",
        category: "cripto",
        event: "cripto_volume",
        metric: "sum",
        target: 20000,
        rewardCoins: 1500,
    },
    {
        id: "cripto_vol_100000",
        name: "Ballena de Mercado",
        desc: "Mueve 100.000 monedas en cripto",
        category: "cripto",
        event: "cripto_volume",
        metric: "sum",
        target: 100000,
        rewardCoins: 7000,
    },
    {
        id: "cripto_sell_25",
        name: "Tomador de Ganancias",
        desc: "Realiza 25 ventas cripto",
        category: "cripto",
        event: "cripto_sell_count",
        metric: "sum",
        target: 25,
        rewardCoins: 2500,
    },
    {
        id: "ttcl_holder_500",
        name: "Ballena TTCL",
        desc: "Mantén 500 TTCL",
        category: "cripto",
        event: "ttcl_hold_max",
        metric: "max",
        target: 500,
        rewardCoins: 1800,
        hidden: true,
    },
    {
        id: "ttcl_holder_2000",
        name: "Titán TTCL",
        desc: "Mantén 2000 TTCL",
        category: "cripto",
        event: "ttcl_hold_max",
        metric: "max",
        target: 2000,
        rewardCoins: 9000,
        hidden: true,
    },
    {
        id: "tienda_primera",
        name: "Cliente",
        desc: "Compra tu primer objeto",
        category: "tienda",
        event: "tienda_buy_count",
        metric: "sum",
        target: 1,
        rewardCoins: 120,
    },
    {
        id: "tienda_20",
        name: "Comprador Compulsivo",
        desc: "Realiza 20 compras",
        category: "tienda",
        event: "tienda_buy_count",
        metric: "sum",
        target: 20,
        rewardCoins: 1100,
    },
    {
        id: "tienda_50",
        name: "Coleccionista",
        desc: "Realiza 50 compras",
        category: "tienda",
        event: "tienda_buy_count",
        metric: "sum",
        target: 50,
        rewardCoins: 3200,
    },
    {
        id: "tienda_5000",
        name: "Mecenas",
        desc: "Gasta 5.000 en tienda",
        category: "tienda",
        event: "tienda_spent",
        metric: "sum",
        target: 5000,
        rewardCoins: 1300,
    },
    {
        id: "tienda_20000",
        name: "Patrocinador",
        desc: "Gasta 20.000 en tienda",
        category: "tienda",
        event: "tienda_spent",
        metric: "sum",
        target: 20000,
        rewardCoins: 6000,
    },
    // 🍿 Plex: se calculan con el historial de Tautulli de quien tiene la cuenta vinculada (systems/plexHistorial).
    // Todos son "max": el evento trae el total actual (horas, películas...), no lo que se suma.
    // Dificultad (systems/plexIdiomas): facil 🟢 · normal 🟡 · gordo 🎰 ("Gordo del Plex").
    ...[
        ["plex_horas_10", "Palomitas en mano", "Ve 10 horas en Plex", "plex_horas", 10, 300, "facil"],
        ["plex_horas_100", "Cinéfilo", "Ve 100 horas en Plex", "plex_horas", 100, 1500, "normal"],
        ["plex_horas_500", "Okupa del sofá", "Ve 500 horas en Plex", "plex_horas", 500, 5000, "gordo"],
        ["plex_horas_1000", "Leyenda del sofá", "Ve 1.000 horas en Plex", "plex_horas", 1000, 10000, "gordo"],
        ["plex_pelis_1", "Se apagan las luces", "Ve tu primera película entera", "plex_peliculas", 1, 100, "facil"],
        ["plex_pelis_25", "Socio del videoclub", "Ve 25 películas distintas", "plex_peliculas", 25, 1200, "normal"],
        ["plex_pelis_100", "Filmoteca andante", "Ve 100 películas distintas", "plex_peliculas", 100, 4000, "gordo"],
        ["plex_eps_50", "Enganchado", "Ve 50 episodios distintos", "plex_episodios", 50, 800, "facil"],
        ["plex_eps_250", "Seriéfilo", "Ve 250 episodios distintos", "plex_episodios", 250, 3000, "normal"],
        ["plex_eps_1000", "Previously on...", "Ve 1.000 episodios distintos", "plex_episodios", 1000, 9000, "gordo"],
        ["plex_series_10", "Picoteo de series", "Ve episodios de 10 series distintas", "plex_series", 10, 1000, "facil"],
        ["plex_series_30", "Zapping infinito", "Ve episodios de 30 series distintas", "plex_series", 30, 3500, "normal"],
        ["plex_maraton_6", "Maratón", "Ve 6 horas en un mismo día", "plex_maraton", 6, 800, "normal"],
        ["plex_maraton_10", "Sin pestañear", "Ve 10 horas en un mismo día", "plex_maraton", 10, 2000, "gordo", true],
        ["plex_atracon_5", "Atracón", "Ve 5 episodios de la misma serie en un día", "plex_atracon", 5, 700, "facil"],
        [
            "plex_atracon_10",
            "Temporada de una sentada",
            "Ve 10 episodios de la misma serie en un día",
            "plex_atracon",
            10,
            1800,
            "normal",
            true,
        ],
        [
            "plex_noche_5",
            "Noctámbulo",
            "Ve algo de madrugada (entre las 3 y las 6) en 5 noches distintas",
            "plex_noctambulo",
            5,
            900,
            "normal",
            true,
        ],
        // Fases 2 y 3: salen de las fichas de Tautulli (systems/plexTrofeos). Lo que es anime lo dicen sus bibliotecas.
        ["plex_completas_1", "Créditos finales", "Termina una serie entera (sin contar anime)", "plex_series_completas", 1, 400, "facil"],
        [
            "plex_completas_5",
            "Sin cabos sueltos",
            "Termina 5 series enteras (sin contar anime)",
            "plex_series_completas",
            5,
            1500,
            "normal",
        ],
        ["plex_completas_15", "Completista", "Termina 15 series enteras (sin contar anime)", "plex_series_completas", 15, 4000, "gordo"],
        ["plex_anime_pelis_1", "Primera de anime", "Ve tu primera película de anime", "plex_anime_peliculas", 1, 150, "facil"],
        ["plex_anime_pelis_10", "Otaku de cine", "Ve 10 películas de anime distintas", "plex_anime_peliculas", 10, 1200, "normal"],
        [
            "plex_anime_pelis_25",
            "Sensei de la gran pantalla",
            "Ve 25 películas de anime distintas",
            "plex_anime_peliculas",
            25,
            3000,
            "gordo",
        ],
        ["plex_anime_series_3", "Opening en bucle", "Ve episodios de 3 series de anime distintas", "plex_anime_series", 3, 600, "facil"],
        [
            "plex_anime_series_10",
            "Otaku confirmado",
            "Ve episodios de 10 series de anime distintas",
            "plex_anime_series",
            10,
            2000,
            "normal",
        ],
        ["plex_anime_eps_100", "Relleno incluido", "Ve 100 episodios de anime distintos", "plex_anime_episodios", 100, 1200, "normal"],
        ["plex_anime_eps_500", "Arco infinito", "Ve 500 episodios de anime distintos", "plex_anime_episodios", 500, 4000, "gordo"],
        ["plex_anime_completas_1", "Sayonara", "Termina una serie de anime entera", "plex_anime_completas", 1, 500, "facil"],
        ["plex_anime_completas_5", "Nakama", "Termina 5 series de anime enteras", "plex_anime_completas", 5, 2500, "normal"],
        // Sociales (systems/plexTrofeos.sociales): con los demás y con lo que acaba de llegar a Plex.
        [
            "plex_compartido_1",
            "Cine compartido",
            "Ve la misma película que otro vinculado el mismo día",
            "plex_cine_compartido",
            1,
            300,
            "facil",
        ],
        [
            "plex_compartido_10",
            "Sesión doble",
            "Ve la misma película que otro vinculado el mismo día, 10 veces",
            "plex_cine_compartido",
            10,
            1500,
            "normal",
        ],
        ["plex_spoilers_1", "Sin spoilers", "Ve algo en las 24 h desde que llega a Plex", "plex_sin_spoilers", 1, 200, "facil"],
        [
            "plex_spoilers_25",
            "Al día",
            "Ve 25 episodios o películas en las 24 h desde que llegan a Plex",
            "plex_sin_spoilers",
            25,
            1500,
            "normal",
        ],
        [
            "plex_spoilers_100",
            "Inmune a los spoilers",
            "Ve 100 episodios o películas en las 24 h desde que llegan a Plex",
            "plex_sin_spoilers",
            100,
            5000,
            "gordo",
        ],
        [
            "plex_primero_1",
            "Primero del servidor",
            "Sé el primero del servidor en ver un estreno (algo en su primera semana en Plex)",
            "plex_primero",
            1,
            300,
            "facil",
        ],
        [
            "plex_primero_25",
            "Estreno en primera fila",
            "Sé el primero del servidor en ver 25 estrenos (en su primera semana en Plex)",
            "plex_primero",
            25,
            2500,
            "normal",
        ],
    ].map(([id, name, desc, event, target, rewardCoins, dificultad, hidden]) => ({
        id,
        name,
        desc,
        category: "plex",
        event,
        metric: "max",
        target,
        rewardCoins,
        dificultad,
        ...(hidden ? { hidden: true } : {}),
    })),
    // Por idioma (inglés, VOSE, castellano y las versiones del anime): systems/plexIdiomas.
    ...require("../plexIdiomas").logrosFijos(),
];

module.exports = { CATALOG };
