// Lista de ajustes del servidor y cómo es cada uno (datos, sin lógica).

const DEFAULT_FLAT = {
    "duende.model": "",
    "duende.temperature": 0.7,
    "duende.history_limit": 20,
    "duende.allowed_channel_id": "",
    "duende.espontaneo_enabled": 1,
    "duende.espontaneo_channel_id": "",
    "duende.madrugada_activa": false,
    "duende.madrugada_desde": 0,
    "duende.madrugada_hasta": 7,
    "duende.canales_formales": "",

    "cripto.fee_buy_pct": 1,
    "cripto.fee_sell_pct": 1,
    "cripto.cooldown_buy_sec": 0,
    "cripto.cooldown_sell_sec": 0,
    "cripto.min_buy": 100,
    "cripto.max_buy": 500000,
    "cripto.min_sell": 100,
    "cripto.max_sell": 500000,

    "casino.min_bet": 10,
    "casino.max_bet": 100000,
    "casino.global_cooldown_sec": 0,
    "casino.daily_limit": 0,
    "casino.rtp_blackjack": 100,
    "casino.rtp_tragaperras": 100,
    "casino.rtp_ruleta": 100,
    "casino.rtp_adivinar": 100,

    "tienda.enabled": true,
    "tienda.buy_cooldown_sec": 0,
    "tienda.daily_limit": 0,
    "tienda.notif_channel_id": "",

    "logros.enabled": true,
    "logros.notify_channel_id": "",
    "logros.reward_multiplier": 1,
    "logros.disabled_categories": "",

    "plex.tautulli_url": "",
    "plex.tautulli_api_key": "",
    "plex.novedades_channel_id": "",
    "plex.bibliotecas_anime": "",
    "plex.ranking_canal": "",
    "plex.ranking_ultima_semana": "",
    "plex.importacion_pct": 50,
    "plex.rol_gordos_1": "",
    "plex.rol_gordos_5": "",
    "plex.rol_gordos_10": "",

    "seerr.url": "",
    "seerr.api_key": "",
    "seerr.daily_request_limit": 5,
    "seerr.avisar_disponible": true,

    "diario.enabled": true,
    "diario.base": 100,
    "diario.por_dia_racha": 20,
    "diario.tope": 500,

    "apuestas.canal_resultados": "",
    "apuestas.recordatorio": true,
    "apuestas.recordatorio_min": 30,
    "apuestas.tope_diario": 0,
    "apuestas.max_partido": 0,
    "apuestas.destacado": true,
    "apuestas.destacado_dia": "",

    "alertas.enabled": true,
    "alertas.admin_ids": "",

    "clasificacion.canal": "",
    "clasificacion.premio": 500,
    "clasificacion.ultima_semana": "",
    "liga.premio_1": 5000,
    "liga.premio_2": 2500,
    "liga.premio_3": 1000,
    "eventos.xp_activo": false,
    "eventos.xp_mult": 2,
    "eventos.xp_desde": 20,
    "eventos.xp_hasta": 22,
    "eventos.casino_activo": false,
    "eventos.casino_pct": 150,
};

const KEY_TYPES = {
    "duende.model": "string",
    "duende.temperature": "number",
    "duende.history_limit": "number",
    "duende.allowed_channel_id": "string",
    "duende.espontaneo_enabled": "number",
    "duende.espontaneo_channel_id": "string",
    "duende.madrugada_activa": "boolean",
    "duende.madrugada_desde": "number",
    "duende.madrugada_hasta": "number",
    "duende.canales_formales": "string",

    "cripto.fee_buy_pct": "number",
    "cripto.fee_sell_pct": "number",
    "cripto.cooldown_buy_sec": "number",
    "cripto.cooldown_sell_sec": "number",
    "cripto.min_buy": "number",
    "cripto.max_buy": "number",
    "cripto.min_sell": "number",
    "cripto.max_sell": "number",

    "casino.min_bet": "number",
    "casino.max_bet": "number",
    "casino.global_cooldown_sec": "number",
    "casino.daily_limit": "number",
    "casino.rtp_blackjack": "number",
    "casino.rtp_tragaperras": "number",
    "casino.rtp_ruleta": "number",
    "casino.rtp_adivinar": "number",

    "tienda.enabled": "boolean",
    "tienda.buy_cooldown_sec": "number",
    "tienda.daily_limit": "number",
    "tienda.notif_channel_id": "string",

    "logros.enabled": "boolean",
    "logros.notify_channel_id": "string",
    "logros.reward_multiplier": "number",
    "logros.disabled_categories": "string",

    "plex.tautulli_url": "string",
    "plex.tautulli_api_key": "string",
    "plex.novedades_channel_id": "string",
    "plex.bibliotecas_anime": "string",
    "plex.ranking_canal": "string",
    "plex.ranking_ultima_semana": "string",
    "plex.importacion_pct": "number",
    "plex.rol_gordos_1": "string",
    "plex.rol_gordos_5": "string",
    "plex.rol_gordos_10": "string",

    "seerr.url": "string",
    "seerr.api_key": "string",
    "seerr.daily_request_limit": "number",
    "seerr.avisar_disponible": "boolean",

    "diario.enabled": "boolean",
    "diario.base": "number",
    "diario.por_dia_racha": "number",
    "diario.tope": "number",

    "apuestas.canal_resultados": "string",
    "apuestas.recordatorio": "boolean",
    "apuestas.recordatorio_min": "number",
    "apuestas.tope_diario": "number",
    "apuestas.max_partido": "number",
    "apuestas.destacado": "boolean",
    "apuestas.destacado_dia": "string",

    "alertas.enabled": "boolean",
    "alertas.admin_ids": "string",

    "clasificacion.canal": "string",
    "clasificacion.premio": "number",
    "clasificacion.ultima_semana": "string",
    "liga.premio_1": "number",
    "liga.premio_2": "number",
    "liga.premio_3": "number",
    "eventos.xp_activo": "boolean",
    "eventos.xp_mult": "number",
    "eventos.xp_desde": "number",
    "eventos.xp_hasta": "number",
    "eventos.casino_activo": "boolean",
    "eventos.casino_pct": "number",
};

module.exports = { DEFAULT_FLAT, KEY_TYPES };
